import moment from "moment";
import { Content } from "pdfmake";
import { v4 } from "uuid";
import { describe, it, expect } from "vitest";

import { defaultSettings, FontFamily, type TimekeepSettings } from "@/settings";

import { createPdfDefinition } from "./definition";

import { defaultTimekeep, TimeEntry, type Timekeep } from "@/timekeep/schema";

function createSettings(): TimekeepSettings {
	return {
		...defaultSettings,
		pdfTitle: "My Timesheet",
		pdfFontFamily: FontFamily.ROBOTO,
		pdfFootnote: "Generated by Timekeep",
	};
}

describe("createPdfDefinition", () => {
	it("creates a valid PDF definition structure", () => {
		const timekeep: Timekeep = defaultTimekeep();

		const settings = createSettings();
		const now = moment("2024-01-01T12:00:00");

		const result = createPdfDefinition(timekeep, settings, now);

		expect(result).toHaveProperty("content");
		expect(result).toHaveProperty("footer");
		expect(result).toHaveProperty("styles");
		expect(result.pageSize).toBe("A4");
		expect(result.pageMargins).toBe(15);
	});

	it("includes header with title and timesheet label", () => {
		const timekeep: Timekeep = defaultTimekeep();

		const settings = createSettings();
		const now = moment();

		const result = createPdfDefinition(timekeep, settings, now);

		const header = (result.content as Content[])[0] as any;

		expect(header[0].columns[0].text).toBe("My Timesheet");
		expect(header[0].columns[1].text).toBe("Timesheet");
	});

	it("renders table with entries and total row", () => {
		const timekeep: Timekeep = {
			entries: [
				{
					id: v4(),
					name: "Test Entry 1",
					startTime: moment("2024-01-01T10:00:00"),
					endTime: moment("2024-01-01T11:00:00"),
					subEntries: null,
				},
				{
					id: v4(),
					name: "Test Entry 2",
					startTime: moment("2024-01-01T10:00:00"),
					endTime: moment("2024-01-01T11:00:00"),
					subEntries: null,
				},
			],
		} as Timekeep;

		const settings = createSettings();
		const now = moment();

		const result = createPdfDefinition(timekeep, settings, now);

		const table = ((result.content as Content[])[1] as any).table;

		// header + 2 rows + total row
		expect(table.body.length).toBe(1 + 2 + 1);

		const totalRow = table.body[table.body.length - 1];
		expect(totalRow[0].text).toBe("Total");
	});

	it("handles nested subEntries with increased depth (margin)", () => {
		const child = {
			id: v4(),
			name: "Child",
			startTime: moment("2024-01-01T10:00:00"),
			endTime: moment("2024-01-01T11:00:00"),
			subEntries: null,
		};

		const parent = {
			id: v4(),
			name: "Test Entry 1",
			startTime: null,
			endTime: null,
			subEntries: [child],
		};

		const timekeep: Timekeep = {
			entries: [parent],
		} as Timekeep;

		const settings = createSettings();
		const now = moment();

		const result = createPdfDefinition(timekeep, settings, now);

		const table = ((result.content as any)[1] as any).table;

		const rows = table.body;

		// Row 1 = header
		// Row 2 = parent
		// Row 3 = child
		const parentRow = rows[1];
		const childRow = rows[2];

		expect(parentRow[0].marginLeft || 0).toBe(0);
		expect(childRow[0].marginLeft).toBeGreaterThan(0);
	});

	it("handles entries ", () => {
		const entry = {
			id: v4(),
			name: "Test Entry 1",
			startTime: moment("2024-01-01T10:00:00"),
			endTime: moment("2024-01-01T11:00:00"),
			subEntries: null,
		};

		const timekeep: Timekeep = {
			entries: [entry],
		} as Timekeep;

		const settings = createSettings();
		const now = moment("2024-01-01T11:00:00");

		const result = createPdfDefinition(timekeep, settings, now);

		const table = ((result.content as Content[])[1] as any).table;
		const row = table.body[1];

		expect(row[1].text).toBe("01/01/2024 10:00");
		expect(row[2].text).toBe("01/01/2024 11:00");
	});

	it("handles entries without startTime", () => {
		const entry = {
			id: v4(),
			name: "Test Entry 1",
			startTime: null,
			endTime: null,
			subEntries: null,
		};

		const timekeep: Timekeep = {
			entries: [entry],
		} as Timekeep;

		const settings = createSettings();
		const now = moment();

		const result = createPdfDefinition(timekeep, settings, now);

		const table = ((result.content as Content[])[1] as any).table;
		const row = table.body[1];

		expect(row[1].text).toBe("");
		expect(row[2].text).toBe("");
	});

	it("handles entries without endTime", () => {
		const entry = {
			id: v4(),
			name: "Test Entry 1",
			startTime: moment("2024-01-01T10:00:00"),
			endTime: null,
			subEntries: null,
		};

		const timekeep: Timekeep = {
			entries: [entry],
		} as Timekeep;

		const settings = createSettings();
		const now = moment("2024-01-01T11:00:00");

		const result = createPdfDefinition(timekeep, settings, now);

		const table = ((result.content as Content[])[1] as any).table;
		const row = table.body[1];

		expect(row[1].text).toBe("01/01/2024 10:00");
		expect(row[2].text).toBe("01/01/2024 11:00");
	});

	it("creates a working footer function", () => {
		const timekeep: Timekeep = {
			entries: [],
		} as Timekeep;

		const settings = createSettings();
		const now = moment();

		const result = createPdfDefinition(timekeep, settings, now);

		const footerFn = result.footer as any;

		const footer = footerFn(2, 5);

		expect(footer.columns[0].text).toBe("Generated by Timekeep");
		expect(footer.columns[1].text).toBe("2 of 5");
	});

	it("applies alternating/group row background logic", () => {
		const parent = {
			id: v4(),
			name: "Test Entry 1",
			startTime: null,
			endTime: null,
			subEntries: [
				{
					id: v4(),
					name: "Child",
					startTime: moment("2024-01-01T10:00:00"),
					endTime: moment("2024-01-01T11:00:00"),
					subEntries: null,
				},
				{
					id: v4(),
					name: "Child",
					startTime: moment("2024-01-01T10:00:00"),
					endTime: moment("2024-01-01T11:00:00"),
					subEntries: null,
				},
			],
		};

		const timekeep: Timekeep = {
			entries: [parent],
		} as Timekeep;

		const settings = createSettings();
		const now = moment();

		const result = createPdfDefinition(timekeep, settings, now);

		const layout = ((result.content as Content[])[1] as any).layout;

		// header row
		expect(layout.fillColor(0)).toBe("#ececec");

		// parent row (group)
		expect(layout.fillColor(1)).toBe("#f4f4f4");

		// child row (default)
		expect(layout.fillColor(2)).toBe("#ffffff");

		// out of bounds (default)
		expect(layout.fillColor(-1)).toBe("#ffffff");
		expect(layout.fillColor(999)).toBe("#ffffff");
	});

	it("handles empty entries", () => {
		const timekeep: Timekeep = {
			entries: [],
		} as Timekeep;

		const settings = createSettings();
		const now = moment();

		const result = createPdfDefinition(timekeep, settings, now);

		const table = ((result.content as Content[])[1] as any).table;

		// header + total row only
		expect(table.body.length).toBe(2);
	});

	it("padding should be defined", () => {
		const timekeep: Timekeep = {
			entries: [],
		} as Timekeep;

		const settings = createSettings();
		const now = moment();

		const result = createPdfDefinition(timekeep, settings, now);

		const table = (result.content as Content[])[1] as any;

		expect(table.layout.paddingBottom).toBeDefined();
		expect(table.layout.paddingLeft).toBeDefined();
		expect(table.layout.paddingTop).toBeDefined();
		expect(table.layout.paddingRight).toBeDefined();
		expect(table.layout.paddingRight).toBeDefined();
		expect(table.layout.paddingRight()).toBe(8);
	});

	it("renders links correctly inside the entry name", () => {
		const entry: TimeEntry = {
			id: "1",
			name: "Check this [[https://example.com]]",
			startTime: null,
			endTime: null,
			subEntries: [],
		};

		const timekeep: Timekeep = {
			entries: [entry],
		};

		const settings = createSettings();
		const now = moment();

		const result = createPdfDefinition(timekeep, settings, now);

		const table = ((result.content as Content[])[1] as any).table;
		const row = table.body[1];

		const nameCell = row[0];
		const contentArray = nameCell.text;

		expect(Array.isArray(contentArray)).toBe(true);

		const linkSegment = contentArray.find(
			(segment: any) => typeof segment === "object" && segment.link
		);

		expect(linkSegment).toBeDefined();
		expect(linkSegment.link).toBe("https://example.com");
		expect(linkSegment.text).toBe("https://example.com");
	});
});
