name: Build
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
permissions:
    contents: read
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Use Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "20"

            - name: Cache node modules
              uses: actions/cache@v5
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build
