name: Release Obsidian plugin
on:
    push:
        tags:
            - "*"

permissions:
    contents: write
    attestations: write
    artifact-metadata: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Use Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "20"

            - name: setup pnpm and caching
              uses: pnpm/action-setup@v6

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm run build

            - name: Generate artifact attestation
              uses: actions/attest@v4
              with:
                  subject-path: |
                      dist/main.js
                      dist/manifest.json
                      dist/styles.css

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"
                  gh release create "$tag" \
                    --title="$tag" \
                    --draft \
                    dist/main.js dist/manifest.json dist/styles.css
